import { lazy } from "react";
export { default as counterReducer } from "../features/counter/counterSlice";
export { default as searchbarReducer } from "../features/Searchbar/searchbarSlice";
export { default as categoryReducer } from "../features/Category/categorySlice";
export { default as videosReducer } from "../features/Videos/videoSlice";
export { default as vidIdReducer } from "../features/VidIds/vidIdsSlice";
export { default as channelIdReducer } from "../features/ChannelIds/channelidsSlice";
export { default as searchReducer } from "../features/Search/searchSlice";
export { default as channelsReducer } from "../features/Channels/channelsSlice";
export { default as suggestedReducer } from "../features/Suggested/suggestedSlice";
export { default as commentsReducer } from "../features/Comments/commentsSlice";
export { default as currChannelReducer } from "../features/CurrChannel/currChannelSlice";
export const Feed = lazy(() => import("./Feed"));
export const ChannelDetail = lazy(() => import("./ChannelDetail"));
export const ChannelCard = lazy(() => import("./ChannelCard"));
export const Navbar = lazy(() => import("./Navbar"));
export const Searchbar = lazy(() => import("./Searchbar"));
export const SearchFeed = lazy(() => import("./SearchFeed"));
export const Sidebar = lazy(() => import("./Sidebar"));
export const Footer = lazy(() => import("./Footer"));
export const VideoCard = lazy(() => import("./VideoCard"));
export const VideoDetail = lazy(() => import("./VideoDetail"));
export const Videos = lazy(() => import("./Videos"));
export const SearchRecommendations = lazy(
  () => import("./SearchRecommendations")
);
export const HelpModal = lazy(() => import("./HelpModal"));
export const ProfileModal = lazy(() => import("./ProfileModal"));
export { default as NewReleasesIcon } from "@mui/icons-material/NewReleases";
export { default as HelpOutlineIcon } from "@mui/icons-material/HelpOutline";
export { default as NotificationsIcon } from "@mui/icons-material/Notifications";
export { default as AccountCircleIcon } from "@mui/icons-material/AccountCircle";
export { default as MenuIcon } from "@mui/icons-material/Menu";
export { default as CloseIcon } from "@mui/icons-material/Close";
export { default as ExpandMoreIcon } from "@mui/icons-material/ExpandMore";
export { default as IconButton } from "@mui/material/IconButton";
export { default as Skeleton } from "@mui/material/Skeleton";
export { default as Stack } from "@mui/material/Stack";
export { default as Category } from "@mui/icons-material/Category";
export { default as Translate } from "@mui/icons-material/Translate";
export { default as Whatshot } from "@mui/icons-material/Whatshot";
export { default as HomeIcon } from "@mui/icons-material/Home";
export { default as MusicNoteIcon } from "@mui/icons-material/MusicNote";
export { default as CodeIcon } from "@mui/icons-material/Code";
export { default as OndemandVideoIcon } from "@mui/icons-material/OndemandVideo";
export { default as SportsEsportsIcon } from "@mui/icons-material/SportsEsports";
export { default as LiveTvIcon } from "@mui/icons-material/LiveTv";
export { default as SchoolIcon } from "@mui/icons-material/School";
export { default as Facebook } from "@mui/icons-material/Facebook";
export { default as FaceRetouchingNaturalIcon } from "@mui/icons-material/FaceRetouchingNatural";
export { default as CheckroomIcon } from "@mui/icons-material/Checkroom";
export { default as GraphicEqIcon } from "@mui/icons-material/GraphicEq";
export { default as TheaterComedyIcon } from "@mui/icons-material/TheaterComedy";
export { default as FitnessCenterIcon } from "@mui/icons-material/FitnessCenter";
export { default as DeveloperModeIcon } from "@mui/icons-material/DeveloperMode";
export { default as SlideshowIcon } from "@mui/icons-material/Slideshow";
